services:
  backend:
    container_name: server
    build: ./src/server
    ports:
      - "3000:3000"
    environment:
      DB_HOST: sqlFinal
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: pfcdb
      PORT: 3000
    volumes:
      - ./src/server:/app
      - /app/node_modules
      - ./src/server/public:/app/public
    working_dir: /app
    command: npm run dev
    depends_on:
      sqlFinal:
        condition: service_healthy

  sqlFinal:
    container_name: sqlFinal
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: pfcdb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
